### ISSUE TITLE
Doesn't build since MyBackEndType Change

### ISSUE THREAD

**Issue by Smithx10** [michaelpq/pg_plugins#34]
Trying to build with 12.2 no longer works after this change was added 25 days ago.

```
   triton:     2020-06-09 15:31:56 installJSONLog main: Installing JSON Log
==> triton: Cloning into '/opt/pgplugins'...
    triton: gcc -std=gnu99 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -m64 -fPIC -I. -I./ -I/opt/postgresql/12.2/include/server -I/opt/postgresql/12.2/include/internal    -c -o jsonlog.o jsonlog.c
==> triton: jsonlog.c: In function 'write_jsonlog':
==> triton: jsonlog.c:398:48: error: 'MyBackendType' undeclared (first use in this function)
==> triton:    if (Logging_collector && redirection_done && MyBackendType != B_LOGGER)
==> triton:                                                 ^
==> triton: jsonlog.c:398:48: note: each undeclared identifier is reported only once for each function it appears in
==> triton: jsonlog.c:398:65: error: 'B_LOGGER' undeclared (first use in this function)
==> triton:    if (Logging_collector && redirection_done && MyBackendType != B_LOGGER)
==> triton:                                                                  ^
    triton: <builtin>: recipe for target 'jsonlog.o' failed
==> triton: make: *** [jsonlog.o] Error 1

```

**Comment by michaelpq** [comment]
That's mentioned in the README of the project:
Note that some modules may fail to compile because of missing dependencies or a version of
PostgreSQL code incompatible with the module. You may want to compile individually modules if that is the case. In all cases each plugin is maintained to be compatible with the latest version of PostgreSQL.

And here Postgres 13 applies.
